services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: govtech
      DB_PASSWORD:
      DB_NAME: financial_assistance
      GIN_MODE: release
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx/wait-for-it.sh:/wait-for-it.sh
      - ./frontend/build:/usr/share/nginx/html # Serve static files
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "/wait-for-it.sh app:8080 --timeout=30 -- nginx -g 'daemon off;'",
      ]
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: govtech
      POSTGRES_PASSWORD:
      POSTGRES_DB: financial_assistance
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
