name: Go CI with Postgres

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download

      - name: Wait for Postgres
        run: until pg_isready -h 127.0.0.1 -U testuser -d test_db; do sleep 1; done

      - name: Enable uuid-ossp extension
        run: |
          export PGPASSWORD=password123
          psql -h 127.0.0.1 -U testuser -d test_db -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"

      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_USER: testuser
          DB_PASSWORD: password123
          DB_NAME: test_db
        run: go test ./...
